// Code generated by goctl. DO NOT EDIT.
// Source: productServer.proto

package server

import (
	"context"

	"www.genji.xin/backend/CareZero/productServer/internal/logic"
	"www.genji.xin/backend/CareZero/productServer/internal/svc"
	"www.genji.xin/backend/CareZero/productServer/product"
)

type ProductCatalogServiceServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductCatalogServiceServer
}

func NewProductCatalogServiceServer(svcCtx *svc.ServiceContext) *ProductCatalogServiceServer {
	return &ProductCatalogServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductCatalogServiceServer) ListProducts(ctx context.Context, in *product.ListProductsReq) (*product.ListProductsResp, error) {
	l := logic.NewListProductsLogic(ctx, s.svcCtx)
	return l.ListProducts(in)
}

func (s *ProductCatalogServiceServer) GetProduct(ctx context.Context, in *product.GetProductReq) (*product.GetProductResp, error) {
	l := logic.NewGetProductLogic(ctx, s.svcCtx)
	return l.GetProduct(in)
}

func (s *ProductCatalogServiceServer) SearchProducts(ctx context.Context, in *product.SearchProductsReq) (*product.SearchProductsResp, error) {
	l := logic.NewSearchProductsLogic(ctx, s.svcCtx)
	return l.SearchProducts(in)
}
